model:
  arch: mlp
  d_model: 16
  n_layers: 1
  act_fn: relu


optim:
  lr: 3.0e-4
  wd: 0.1
  betas: [0.9, 0.95]


data: 
  task: sparse_parity
  
train:
  seed: 42
  device: "cuda:0"
  train_iters: 500
  eval_iters: 50
  eval_every: 50
  save_every: 50

wandb:
  project: toy-scaling
  group: dev-testing
  name: first-test
  entity: haileyschoelkopf